backfill:
  arxiv:
    continuation: null
    covered_from: '2023-01-01T00:00:00Z'
  huggingface:
    continuation:
      cursor: eyJkYXRlIjoiMjAyNC0wOC0yMSIsInBhZ2UiOjEsInNvdXJjZV9jb25zdW1lZCI6MjIyfQ
      window_end: '2024-09-17T18:59:56.896465Z'
      window_start: '2023-09-18T18:59:56.896465Z'
    covered_from: '2024-09-17T18:59:56.896465Z'
continuations: {}
failures: {}
